FROM maven:3.9.9-eclipse-temurin-17 AS scm
RUN git clone https://github.com/spring-projects/spring-petclinic.git
WORKDIR /
FROM maven:3.9.9-eclipse-temurin-17 AS builder
COPY --from=scm /spring-petclinic /spring-petclinic
WORKDIR /spring-petclinic
RUN mvn clean package
CMD [ "sleep", "1d" ]